### ISSUE TITLE
v1.2.0 is broken.

### ISSUE THREAD

**Issue by d-oliveros** [hontas/gulp-task-loader#4]
After updating from 1.0.8, the module is looking for the tasks relatively to its installation folder.

This doesn't work:
`taskLoader(path.join(__dirname, 'tasks'));`

Stack trace:

```
Error: Cannot find module '/home/myuser/myfolder/myapp/node_modules/gulp-task-loader/home/myuser/myfolder/myapp/tasks/angularTemplates.js
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadTask (/home/myuser/myfolder/myapp/node_modules/gulp-task-loader/index.js:44:14)
    at loadTasks (/home/myuser/myfolder/myapp/node_modules/gulp-task-loader/index.js:65:4)
    at Array.forEach (native)
    at module.exports (/home/myuser/myfolder/myapp/node_modules/gulp-task-loader/index.js:77:4)
    at Object.<anonymous> (/home/myuser/myfolder/myapp/gulpfile.js:20:1)

```

**Comment by d-oliveros** [comment]
Tried with `taskLoader('tasks');` and `taskLoader(./'tasks');` too. 

For the records, this is my gulpfile:

``` js
var gulp = require('gulp');
var path = require('path');
var taskLoader = require('gulp-task-loader');

gulp.task('default', [
    'lint'
]);

gulp.task('build', [
    'minifyJS',
    'minifyCSS'
]);

gulp.task('start', [
    'nodemon',
    'watchify'
]);

// Require the tasks in ./tasks
taskLoader(path.join(__dirname, 'tasks'));
```

**Comment by archr** [comment]
Fixed in PR https://github.com/hontas/gulp-task-loader/pull/5

**Comment by d-oliveros** [comment]
Thanks @archr :dancers:

**Comment by archr** [comment]
🍺

**Comment by hontas** [comment]
thanks for the help @archr - this one slipped by me. :+1:
