### ISSUE TITLE
1.4.0 breaks sub task functionality.

### ISSUE THREAD

**Issue by gerlocian** [hontas/gulp-task-loader#12]
We've been using gulp-task-loader for our project since 1.3.1 and we have the following folder setup.

```
src/
    gulp/
        tasks/
            build/
                fonts.js
                images.js
                sass.js
                templates.js
            test/
                e2e.js
                lint.js
                unit.js
```

We have gulp-task-loader configured to look for tasks in src/gulp/tasks/

`require ('gulp-task-loader')({dir: './src/gulp/tasks');` 

After updating to 1.4.0, we started receiving the following error:

```
Error: Cannot find module '/home/portiz/repos/project/src/gulp/tasks/fonts.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadTask (/home/portiz/repos/project/node_modules/gulp-task-loader/index.js:41:14)
    at loadTasks (/home/portiz/repos/project/node_modules/gulp-task-loader/index.js:66:4)
    at /home/portiz/repos/project/node_modules/gulp-task-loader/index.js:71:6
    at Array.forEach (native)
    at loadTasks (/home/portiz/repos/project/node_modules/gulp-task-loader/index.js:70:6)
    at /home/portiz/repos/project/node_modules/gulp-task-loader/index.js:71:6
```

Stepping through and debugging our gulp tasks, we found that the gulp-task-loader was truncating the "build" path node from the task location. It occurs somewhere on line 66:

`loadTask(currentPath.split('/').slice(opts.dir.split('/').length, -1), file);`

Is there something wrong with gulp-task-loader, or are we doing something wrong with the new version on our end?

**Comment by dougludlow** [comment]
Seeing the same issue.

**Comment by dougludlow** [comment]
Reverted back to v1.3.1 and it loads just fine.

**Comment by gerlocian** [comment]
Yep, that's what we did too, however I'm interested in seeing the fix for this. I'm looking at investigating a solution now.

**Comment by gerlocian** [comment]
Added a pull request that might resolve the issue. Take a look and let me know.

https://github.com/hontas/gulp-task-loader/pull/13

**Comment by nerdybeast** [comment]
I'm seeing this issue as well but went ahead and flattened my gulp-tasks folder for now in order to continue using v1.4.0.

**Comment by hontas** [comment]
Sorry about my late reply. This should be fixed in 1.4.1
